### PR TITLE
major bonk

### PR DESCRIPTION
**Pull request by amitojsingh366**

### CODE REVIEW

**Review by crispyaus — COMMENTED** [review]
why dont you just assign your "interactiveclient" onto the discord.js client so people dont need to create their own event listener just for your package, instead they can just use an event listener from discord.js and you can add a new type to that like buttonClicked for example, would be smarter

**Comment by jzeuzs** [comment]
> why dont you just assign your "interactiveclient" onto the discord.js client so people dont need to create their own event listener just for your package, instead they can just use an event listener from discord.js and you can add a new type to that like buttonClicked for example, would be smarter

This would be unfavorable.

**Comment by crispyaus** [comment]
> > why dont you just assign your "interactiveclient" onto the discord.js client so people dont need to create their own event listener just for your package, instead they can just use an event listener from discord.js and you can add a new type to that like buttonClicked for example, would be smarter
> 
> This would be unfavorable.

It's actually a lot smarter and better for the end user, mind explaining why its "unfavorable"?

**Comment by amitojsingh366** [comment]
> 
> 
> > > why dont you just assign your "interactiveclient" onto the discord.js client so people dont need to create their own event listener just for your package, instead they can just use an event listener from discord.js and you can add a new type to that like buttonClicked for example, would be smarter
> > 
> > 
> > This would be unfavorable.
> 
> It's actually a lot smarter and better for the end user, mind explaining why its "unfavorable"?

can u explain it a little more, i didn't get what you want

**Comment by jzeuzs** [comment]
> > > why dont you just assign your "interactiveclient" onto the discord.js client so people dont need to create their own event listener just for your package, instead they can just use an event listener from discord.js and you can add a new type to that like buttonClicked for example, would be smarter
> > 
> > 
> > This would be unfavorable.
> 
> It's actually a lot smarter and better for the end user, mind explaining why its "unfavorable"?

In that case, you would want to assign a custom id to the button so you would know what button is that. Which is unfavorable and unconvenient.

**Pull request merged**
